name: workflow
on:
  push:
    branch:
      -main
    pull_request:
      branch:
        - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8'
      - uses: actions/setup-node@v1
        with:
          node-version: '18'
      - name: Install Angular program dependencies, Angular global CLI + ng build
        run: cd ./Fromt-end && npm i -g @angular/cli && npm i && ng build -c="main"

      - name: Build test code and install playwright test browser
        run: cd ./BackEnd/FullBackEndTestProject/Test && dotnet build && pwsh bin/Debug/net8.0/playwright.ps1 install --with-deps

      - name: Build and run Web API + getting process ID for shutting down later
        run: cd ./Back-End/FullBackEndTestProject/api && dotnet run & echo "API_PID=$!" >> $GITHUB_ENV
        env:
          pgconn: ${{secrets.PGCONN}}

      - name: Run tests once API is running (sleep interval set to 60 seconds)
        run: cd ./BackEnd/FullBackEndTestProject/Test && sleep 60 && dotnet test
        env:
          pgconn: ${{secrets.PGCONN}}
          
      - name: Shutdown Web API once the tests are done running
        run: kill $API_PID
